# Layer settings for Convolutional-Autoencoder
CAEMNIST:
  features_channels: [16, 32, 32]
  kernels:
  - [3,3]
  - [3,3]
  - [3,3]
  strides:
  - [2,2]
  - [2,2]
  - [2,2]
  paddings:
  - [1,1]
  - [1,1]
  - [1,1]

CAE3:
  features_channels: [8, 16, 16]
  kernels:
  - [5, 5]
  - [3, 3]
  - [3, 3]
  strides:
  - [2, 2]
  - [2, 2]
  - [1, 1]
  paddings:
  - [1, 1]
  - [1, 1]
  - [1, 1]

CAE256:
  features_channels: [ 32, 64, 128, 256]
  kernels:
  - [ 5, 5 ]
  - [ 5, 5 ]
  - [ 5, 5 ]
  - [ 3, 3 ]
  strides:
  - [ 2, 2 ]
  - [ 2, 2 ]
  - [ 2, 2 ]
  - [ 2, 2 ]
  paddings:
  - [ 1, 1 ]
  - [ 1, 1 ]
  - [ 1, 1 ]
  - [ 1, 1 ]







CAE512:
  features_channels: [ 32, 64, 128, 256, 512 ]
  kernels:
  - [ 5, 5 ]
  - [ 5, 5 ]
  - [ 5, 5 ]
  - [ 3, 3 ]
  - [ 3, 3 ]
  strides:
  - [ 2, 2 ]
  - [ 2, 2 ]
  - [ 2, 2 ]
  - [ 1, 1 ]
  - [ 1, 1 ]
  paddings:
  - [ 1, 1 ]
  - [ 1, 1 ]
  - [ 1, 1 ]
  - [ 1, 1 ]
  - [ 1, 1 ]

CAE224:
  features_channels: [ 32, 64, 64, 64]
  kernels:
  - [ 5, 5 ]
  - [ 5, 5 ]
  - [ 3, 3 ]
  - [ 3, 3 ]
  strides:
  - [ 4, 4 ]
  - [ 4, 4 ]
  - [ 2, 2 ]
  - [ 2, 2 ]
  paddings:
  - [ 1, 1 ]
  - [ 1, 1 ]
  - [ 1, 1 ]
  - [ 1, 1 ]



