# Layer settings for Convolutional-Autoencoder
CAE2:
  features_channels: [32, 64]
  kernels:
  - [5,5]
  - [3,3]
  strides:
  - [2,2]
  - [2,2]
  paddings:
  - [1,1]
  - [1,1]

CAE3:
  features_channels: [32, 64, 128]
  kernels:
  - [5, 5]
  - [5, 5]
  - [3, 3]
  strides:
  - [2, 2]
  - [2, 2]
  - [1, 1]
  paddings:
  - [1, 1]
  - [1, 1]
  - [1, 1]






