### CLARO Dataset   ###

seed: 42

data:
  image_size: 256
  channel: 1
  range: [0,1]

  data_dir: data_raw
  interim_dir: interim/claro
  raw_dir: raw/claro
  box_file: data_claro.xlsx
  box_value: max_box #box
  data_info: patients_info_claro.xlsx
  clip:
    min: -1000
    max: 1000
  scale:
    min: -1000
    max: 1000
  convert_to_uint8: False
  scale_to_255: False
